In [1]:
import pandas as pd

In [2]:
model_comparison = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "KNN",
        "Decision Tree",
        "Random Forest",
        "XGBoost"
    ],

    "Test Accuracy": [
        0.9192037470472596,
        0.9285714285714286,
        0.9988290398126464,
        0.9988290398126464,
        0.9976580796252927
    ],

    "Test Precision": [
        0.9215328470153284,
        0.9257246376811594,
        0.9981203007518797,
        0.9981203007518797,
        0.9981167608286252
    ],

    "Test Recall": [
        0.9510357815442562,
        0.9623352165725048,
        1.0,
        1.0,
        0.9981167608286252
    ],

    "Test F1": [
        0.936051899073216,
        0.9436749769159741,
        0.9990592662276576,
        0.9990592662276576,
        0.9981167608286252
    ],

    "Test ROC-AUC": [
        0.9750339624401648,
        0.9820684146391235,
        0.9999912543072537,
        0.9999941695381691,
        0.999825086145074
    ]
})

In [3]:
model_comparison

,Model,Test Accuracy,Test Precision,Test Recall,Test F1,Test ROC-AUC
0,Logistic Regression,0.919204,0.921533,0.951036,0.936052,0.975034
1,KNN,0.928571,0.925725,0.962335,0.943675,0.982068
2,Decision Tree,0.998829,0.998120,1.000000,0.999059,0.999991
3,Random Forest,0.998829,0.998120,1.000000,0.999059,0.999994
4,XGBoost,0.997658,0.998117,0.998117,0.998117,0.999825

In [4]:
model_comparison.sort_values(
    "Test ROC-AUC",
    ascending=False
)

,Model,Test Accuracy,Test Precision,Test Recall,Test F1,Test ROC-AUC
3,Random Forest,0.998829,0.998120,1.000000,0.999059,0.999994
2,Decision Tree,0.998829,0.998120,1.000000,0.999059,0.999991
4,XGBoost,0.997658,0.998117,0.998117,0.998117,0.999825
1,KNN,0.928571,0.925725,0.962335,0.943675,0.982068
0,Logistic Regression,0.919204,0.921533,0.951036,0.936052,0.975034

NameError: name 'rf_grid' is not defined